[
   Prod                          -- _1 KW["-"] KW[">"] _2 _3,
   COMPLETION-Production         -- _1,
   Aliases                       -- KW["aliases"] _1,
   Alias                         -- _1 _2,
   COMPLETION-Grammar            -- _1,
   COMPLETION-Alias              -- _1,
   COMPLETION-Aliases            -- _1,
   CharClass                     -- _1,
   Seq                           -- _1 KW["."] _2,
   Single                        -- _1,
   Alt                           -- _1 KW["|"] _2,
   List                          -- KW["[["] _1 KW["]]"],
   List.1:iter-star-sep          -- _1 KW[","],
   Follow                        -- _1 KW["-/-"] _2,
   Restrictions                  -- KW["restrictions"] _1,
   Reject                        -- KW["reject"],
   Prefer                        -- KW["prefer"],
   Avoid                         -- KW["avoid"],
   COMPLETION-Lookahead          -- _1,
   COMPLETION-Lookaheads         -- _1,
   COMPLETION-Restriction        -- _1,
   COMPLETION-Restrictions       -- _1,
   COMPLETION-Grammar            -- _1,
   COMPLETION-Attribute          -- _1,
   Quoted                        -- _1,
   Unquoted                      -- _1,
   Label                         -- _1 KW[":"] _2,
   COMPLETION-Label              -- _1,
   COMPLETION-Symbol             -- _1,
   UnquotedFun                   -- _1,
   QuotedFun                     -- _1,
   COMPLETION-FunctionName       -- _1,
   Lit                           -- _1,
   CiLit                         -- _1,
   PrefixFun                     -- _1 KW["("] _2 KW[")"] KW["-"] KW[">"] _3 _4,
   PrefixFun.2:iter-star-sep     -- _1 KW[","],
   COMPLETION-Symbol             -- _1,
   COMPLETION-Production         -- _1,
   KernelStartSymbols            -- KW["start-symbols"] _1,
   LexicalStartSymbols           -- KW["lexical"] KW["start-symbols"] _1,
   ContextFreeStartSymbols       -- KW["context-free"] KW["start-symbols"] _1,
   Sort                          -- _1,
   ParameterizedSort             -- _1 KW["[["] _2 KW["]]"],
   ParameterizedSort.2:iter-sep  -- _1 KW[","],
   Sorts                         -- KW["sorts"] _1,
   Numeric                       -- _1,
   Short                         -- _1,
   Top                           -- KW["\\"] KW["TOP"],
   Eof                           -- KW["\\"] KW["EOF"],
   Bot                           -- KW["\\"] KW["BOT"],
   LabelStart                    -- KW["\\"] KW["LABEL_START"],
   COMPLETION-Character          -- _1,
   Range                         -- _1 KW["-"] _2,
   Conc                          -- _1 _2,
   Absent                        -- ,
   Present                       -- _1,
   Simple                        -- KW["["] _1 KW["]"],
   Comp                          -- KW["~"] _1,
   Diff                          -- _1 KW["/"] _2,
   Isect                         -- _1 KW["/"] KW["\\"] _2,
   Union                         -- _1 KW["\\"] KW["/"] _2,
   COMPLETION-CharRange          -- _1,
   COMPLETION-CharRanges         -- _1,
   COMPLETION-OptCharRanges      -- _1,
   COMPLETION-ClarClass          -- _1,
   COMPLETION-CharClass          -- _1,
   CharClass                     -- _1,
   Left                          -- KW["left"],
   Right                         -- KW["right"],
   NonAssoc                      -- KW["non-assoc"],
   Assoc                         -- KW["assoc"],
   Bracket                       -- KW["bracket"],
   Assoc                         -- _1,
   Default                       -- KW["<"] _1 KW[">"],
   Default.1:iter-sep            -- _1 KW[","],
   WithArguments                 -- _1 _2,
   NonTransitive                 -- _1 KW["."],
   SimpleGroup                   -- _1,
   ProdsGroup                    -- KW["{"] _1 KW["}"],
   AssocGroup                    -- KW["{"] _1 KW[":"] _2 KW["}"],
   Chain                         -- _1,
   Chain.1:iter-sep              -- _1 KW[">"],
   Assoc                         -- _1 _2 _3,
   Priorities                    -- KW["priorities"] _1,
   COMPLETION-Associativity      -- _1,
   COMPLETION-Attribute          -- _1,
   COMPLETION-ArgumentIndicator  -- _1,
   COMPLETION-Group              -- _1,
   COMPLETION-Priority           -- _1,
   COMPLETION-Priorities         -- _1,
   COMPLETION-Grammar            -- _1,
   Lifting                       -- KW["`"] _1 KW["`"],
   Empty                         -- KW["("] KW[")"],
   Seq                           -- KW["("] _1 _2 KW[")"],
   Seq.2:iter                    -- _1,
   Opt                           -- _1 KW["?"],
   Iter                          -- _1 KW["+"],
   IterStar                      -- _1 KW["*"],
   IterSep                       -- KW["{"] _1 _2 KW["}"] KW["+"],
   IterStarSep                   -- KW["{"] _1 _2 KW["}"] KW["*"],
   Tuple                         -- KW["<"] _1 KW[","] _2 KW[">"],
   Tuple.2:iter-sep              -- _1 KW[","],
   Func                          -- KW["("] _1 KW["="] KW[">"] _2 KW[")"],
   Alt                           -- _1 KW["|"] _2,
   Strategy                      -- KW["("] _1 KW["-"] KW[">"] _2 KW[")"],
   COMPLETION-Symbol             -- _1,
   Renamings                     -- V  [V vs=2 [KW["["] _1] KW["]"]],
   Renamings.1:iter-star         -- _1,
   Symbol                        -- _1 KW["="] KW[">"] _2,
   Production                    -- _1 KW["="] KW[">"] _2,
   COMPLETION-Renamings          -- _1,
   COMPLETION-Renaming           -- _1,
   Module                        -- KW["module"] _1 _2 _3,
   Module.2:iter-star            -- _1,
   SDFSection                    -- _1,
   Unparameterized               -- _1,
   Parameterized                 -- _1 KW["["] _2 KW["]"],
   Imports                       -- KW["imports"] _1,
   Module                        -- _1,
   COMPLETION-Definition         -- _1,
   COMPLETION-Module             -- _1,
   COMPLETION-Sections           -- _1,
   COMPLETION-Section            -- _1,
   COMPLETION-ModuleName         -- _1,
   COMPLETION-ImpSection         -- _1,
   COMPLETION-Imports            -- _1,
   COMPLETION-Import             -- _1,
   Lexical                       -- KW["lexical"] KW["syntax"] _1,
   Contextfree                   -- KW["context-free"] KW["syntax"] _1,
   Variables                     -- KW["variables"] _1,
   LexVariables                  -- KW["lexical"] KW["variables"] _1,
   Cf                            -- KW["<"] _1 KW["-CF"] KW[">"],
   Lex                           -- KW["<"] _1 KW["-LEX"] KW[">"],
   VarSym                        -- KW["<"] _1 KW["-VAR"] KW[">"],
   Layout                        -- KW["LAYOUT"],
   COMPLETION-Grammar            -- _1,
   COMPLETION-Symbol             -- _1,
   Empty                         -- KW["("] KW["/"] KW[")"],
   COMPLETION-Grammar            -- _1,
   COMPLETION-Symbol             -- _1,
   COMPLETION-Symbols            -- _1,
   Present                       -- KW["e"] _1,
   Absent                        -- ,
   RealCon                       -- _1 KW["."] _2 _3,
   COMPLETION-OptExp             -- _1,
   COMPLETION-RealCon            -- _1,
   Natural                       -- _1,
   Positive                      -- KW["+"] _1,
   Negative                      -- KW["-"] _1,
   COMPLETION-IntCon             -- _1,
   Quoted                        -- _1,
   Unquoted                      -- _1,
   COMPLETION-AFun               -- _1,
   Int                           -- _1,
   Real                          -- _1,
   Fun                           -- _1,
   Appl                          -- _1 KW["("] _2 KW[")"],
   Appl.2:iter-star-sep          -- _1 KW[","],
   PlaceHolder                   -- KW["<"] _1 KW[">"],
   List                          -- KW["["] _1 KW["]"],
   List.1:iter-star-sep          -- _1 KW[","],
   Annotated                     -- _1 _2,
   COMPLETION-ATerm              -- _1,
   Default                       -- KW["{"] _1 KW["}"],
   Default.1:iter-sep            -- _1 KW[","],
   COMPLETION-Annotation         -- _1,
   Default                       -- _1,
   Term                          -- _1,
   Attrs                         -- KW["{"] _1 KW["}"],
   Attrs.1:iter-star-sep         -- _1 KW[","],
   NoAttrs                       -- ,
   Prod                          -- _1 KW["-"] KW[">"] _2 _3,
   Syntax                        -- KW["syntax"] _1,
   COMPLETION-ATermAttribute     -- _1,
   COMPLETION-Attribute          -- _1,
   COMPLETION-Attributes         -- _1,
   COMPLETION-Production         -- _1,
   COMPLETION-Productions        -- _1,
   COMPLETION-Grammar            -- _1,
   Start                         -- KW["<"] KW["START"] KW[">"],
   FileStart                     -- KW["<"] KW["Start"] KW[">"],
   LexicalPriorities             -- KW["lexical"] KW["priorities"] _1,
   ContextFreePriorities         -- KW["context-free"] KW["priorities"] _1,
   LexicalRestrictions           -- KW["lexical"] KW["restrictions"] _1,
   ContextFreeRestrictions       -- KW["context-free"] KW["restrictions"] _1,
   COMPLETION-Symbol             -- _1,
   COMPLETION-Grammar            -- _1,
   COMPLETION-ModuleName         -- _1,
   COMPLETION-Symbols            -- _1,
   COMPLETION-Label              -- _1,
   COMPLETION-ATermAttribute     -- _1,
   NonTransitive                 -- _1 KW["."],
   CompilationUnit               -- _1,
   CompilationUnit.1:iter-star   -- _1,
   COMPLETION-Start              -- _1,
   QuotedConstructor             -- _1,
   COMPLETION-Attribute          -- _1,
   COMPLETION-QuotedConstructor  -- _1,
   WATER                         -- _1,
   WATER                         -- _1,
   WATER                         -- _1,
   COMPLETION-TemplateProduction -- _1,
   COMPLETION-PlaceholderOption  -- _1,
   COMPLETION-PlaceholderOptions -- _1,
   TemplateOptions               -- V  [H  [KW["template"] KW["options"]] _1],
   TemplateOptions.1:iter-star   -- _1,
   NewLines                      -- KW["newlines"] KW[":"] _1,
   None                          -- KW["none"],
   Leading                       -- KW["leading"],
   Trailing                      -- KW["trailing"],
   Separating                    -- KW["separating"],
   KeywordFollowRestriction      -- KW["keyword"] KW["-/-"] _1,
   Tokenize                      -- KW["tokenize"] KW[":"] _1,
   COMPLETION-Section            -- _1,
   COMPLETION-NewlineOptionValue -- _1,
   COMPLETION-TemplateOption     -- _1,
   SimpleRefGroup                -- _1,
   ProdsRefGroup                 -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   ProdsRefGroup.1:iter          -- _1,
   AssocRefGroup                 -- KW["{Associativity"] KW[":"] _1 KW["}"],
   AssocRefGroup.1:iter          -- _1,
   COMPLETION-Group              -- _1,
   TemplateSection               -- V  [H  [KW["templates"]] _1],
   TemplateSection.1:iter-star   -- _1,
   LexicalSyntax                 -- V  [H  [KW["lexical"] KW["syntax"]] _1],
   LexicalSyntax.1:iter-star     -- _1,
   ContextFreeSyntax             -- V  [H  [KW["context-free"] KW["syntax"]] _1],
   ContextFreeSyntax.1:iter-star -- _1,
   SdfProduction                 -- _1 KW["="] _2 _3,
   SdfProductionWithCons         -- _1 KW["="] _2 _3,
   TemplateProduction            -- _1 KW["="] _2 _3,
   TemplateProductionWithCons    -- _1 KW["="] _2 _3,
   Constructor                   -- _1,
   SortCons                      -- _1 KW["."] _2,
   Placeholder                   -- _1 _2 _3 _4,
   Sort                          -- _1,
   None                          -- ,
   Label                         -- _1 KW[":"],
   None                          -- ,
   Star                          -- KW["*"],
   Plus                          -- KW["+"],
   Option                        -- KW["?"],
   NoOptions                     -- ,
   Options                       -- V  [H  [KW[";"]] _1],
   Options.1:iter-sep            -- _1 KW[","],
   Hide                          -- KW["hide"],
   Wrap                          -- KW["wrap"],
   Anchor                        -- KW["anchor"],
   Separator                     -- KW["separator"] KW["="] _1,
   Text                          -- KW["text"] KW["="] _1,
   COMPLETION-Section            -- _1,
   COMPLETION-Grammar            -- _1,
   COMPLETION-SdfProduction      -- _1,
   COMPLETION-TemplateProduction -- _1,
   COMPLETION-Constructor        -- _1,
   COMPLETION-SortCons           -- _1,
   COMPLETION-TemplatePart1      -- _1,
   COMPLETION-TemplatePart2      -- _1,
   COMPLETION-Placeholder        -- _1,
   COMPLETION-PlaceholderSort    -- _1,
   COMPLETION-PlaceholderLabel   -- _1,
   COMPLETION-PlaceholderSuffix  -- _1,
   COMPLETION-PlaceholderOptions -- _1,
   COMPLETION-PlaceholderOption  -- _1
]